name: threenav
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1
  http: ^1.1.0 
  splash_master: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

splash_master:
  # Use to specifies the color for the splash screen
  color: '#FFFFFF'
  # Use to specifies the splash image
  image: 'assets/splash.png'
  # Provides content mode for splash image in iOS
  # iOS content mode options: scaleToFill, scaleAspectFit, scaleAspectFill, redraw, center, top, bottom,
  # left, right, topLeft, topRight, bottomLeft, bottomRight.
  ios_content_mode: 'center'
  # Provides gravity for splash image in Android
  # Android gravity options: center, clip_horizontal, clip_vertical, fill_horizontal, fill, center_vertical, 
  # bottom, fill_vertical, center_horizontal, top, end, left, right, start
  android_gravity: 'center'
  # Use to specifies the splash image
  background_image: 'assets/background_image.jpg'
  # Provided content mode for splash image in background for iOS
  ios_background_content_mode: 'scaleToFill'
  # Provides gravity for background image in Android
  # Android gravity options: center, clip_horizontal, clip_vertical, fill_horizontal, fill, center_vertical, 
  # bottom, fill_vertical, center_horizontal, top, end, left, right, start
  android_background_image_gravity: 'fill'
  # Use to specifies image for android in dark mode
  image_dark_android: 'assets/splash_dark.png'
  # Provides gravity for splash image for Android in dark mode
  android_dark_gravity_key: 'center'
  # Use to specifies the color for the splash screen for Android in dark mode
  color_dark_android: '#000000'
  # Section to specifies the configuration for the splash in Android 12+